# Set env variable:
#export MINK_EXTENSION_PARAMS="base_url=h*"
#run all tests:
#for f in `find src/ -path '*/Features'`; do ./bin/behat -c app/config/behat.yml $f; done
default:
    suites:
        #default:
            #path: %paths.base%/features
            #contexts: [Behat\MinkExtension\Context\MinkContext]
        bugfix:
            type: symfony_bundle
            bundle: 'EspaceMembersMainBundle'
            #contexts: ['EspaceMembersMainBundle\Features\Context\WebContext']
  extensions:
    Behat\Symfony2Extension:
        mink_driver: true
        kernel:
            env: test
            debug: true
    Behat\MinkExtension:
        base_url: 'http://localhost/app_test.php/'
        default_session: 'symfony2'
        #javascript_session: sahi
        browser_name: firefox
        goutte: ~
    #autoload:
        #'': %paths.base%/src
