#FOSUserBundle configuration for SonataAdmin
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: EspaceMembers\MainBundle\Entity\User #Override Sonata\UserBundle\Entity\BaseUser
    group:
        group_class:   EspaceMembers\MainBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager
