security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    acl:
        connection: default

    role_hierarchy:
        ROLE_USER:        [ROLE_USER]
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern:            ^/
            context:            user
            form_login:
                provider:        fos_userbundle
                login_path:      sonata_user_admin_security_login
                use_forward:     false
                check_path:      sonata_user_admin_security_check
                success_handler: user_security.login_success
                failure_path:    sonata_user_admin_security_login 
                use_referer:     true 
                default_target_path: sonata_user_admin_security_login
            logout:
                path:           sonata_user_admin_security_logout
                target:         sonata_user_admin_security_login
            anonymous:          true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/profile, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN, ROLE_USER] }
        - { path: ^/profile/edit-profile, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN, ROLE_USER] }
        - { path: ^/bookmark/.*, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN, ROLE_USER] }
        - { path: ^/.*, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN, ROLE_USER] }

