sonata_user:
    security_acl:     false
    class:
        user: EspaceMembers\MainBundle\Entity\User #Override Sonata\UserBundle\Entity\BaseUser
        group:   EspaceMembers\MainBundle\Entity\Group

    admin:
        user:
            class:          EspaceMembers\MainBundle\Admin\UserAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle

        group:
            class:          EspaceMembers\MainBundle\Admin\GroupAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle

    profile:  # Profile Form (firstname, lastname, etc ...)
        form:
            type:               espacemembers_user_profile
            handler:            sonata.user.profile.form.handler.default
            name:               espacemembers_user_profile_form
            #validation_groups:  [Profile]
        register:
            confirm:
                redirect:
                    route: 'espace_members_teaching'
                    route_parameters: ~
        menu:
            - { route: 'sonata_user_profile_edit', label: 'link_edit_profile', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_profile_edit_authentication', label: 'link_edit_authentication', domain: 'SonataUserBundle'}
