espace_members_filter_teaching:
  resource: "@EspaceMembersMainBundle/Resources/config/routing/filter_teaching_routing.yml"
  prefix: /filter

espace_members_community_page:
  resource: "@EspaceMembersMainBundle/Resources/config/routing/community_routing.yml"
  prefix: /community

espace_members_bookmark_page:
  resource: "@EspaceMembersMainBundle/Resources/config/routing/bookmark_routing.yml"
  prefix: /bookmark

espace_members_teaching_search:
    path:     /search/{page}
    defaults: { _controller: EspaceMembersMainBundle:Teaching:search, page: 1 }
    requirements:
        _method: GET
        page: \d+

espace_members_teaching:
    path:     /{page}
    defaults: { _controller: EspaceMembersMainBundle:Teaching:index, page: 1 }
    requirements:
        _method: GET
        page: \d+

espace_members_playing_teaching:
    pattern:  /playing/teaching/{teaching_id}/teacher/{teacher_id}/event/{event_id}
    defaults: { _controller: EspaceMembersMainBundle:Teaching:play }
    requirements:
        _method: GET
        teaching_id: \d+
        teacher_id:  \d+
        event_id:    \d+
    options:
        expose: true

espace_members_detail_teaching:
    pattern:  /detail/event/{event_id}
    defaults: { _controller: EspaceMembersMainBundle:Teaching:viewDetail }
    requirements:
        _method: GET
        event_id: \d+
    options:
        expose: true

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
