parameters:
    sonata.user.admin.user.class: EspaceMembers\MainBundle\Admin\UserAdmin
    sonata.user.admin.user.entity: EspaceMembers\MainBundle\Entity\User

services:
    getid3:
        class: GetId3\GetId3Core

    sonata.user.admin.group:
        abstract: true
        public: false

    sonata.admin.group:
        class: EspaceMembers\MainBundle\Admin\GroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: EspaceMembers, label: "Group" }
        arguments:
            - ~
            - EspaceMembers\MainBundle\Entity\Group
            - 'SonataAdminBundle:CRUD'

    sonata.admin.teaching:
        class: EspaceMembers\MainBundle\Admin\TeachingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: EspaceMembers, label: "Teaching" }
        arguments:
            - ~
            - EspaceMembers\MainBundle\Entity\Teaching
            - 'SonataAdminBundle:CRUD'

    sonata.admin.voie:
        class: EspaceMembers\MainBundle\Admin\VoieAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: EspaceMembers, label: "Voie" }
        arguments:
            - ~
            - EspaceMembers\MainBundle\Entity\Voie
            - 'SonataAdminBundle:CRUD'

    sonata.admin.tag:
        class: EspaceMembers\MainBundle\Admin\TagAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: EspaceMembers,  label: "Tag", show_in_dashboard: false}
        arguments:
            - ~
            - EspaceMembers\MainBundle\Entity\Tag
            - 'SonataAdminBundle:CRUD'

    sonata.admin.category:
        class: EspaceMembers\MainBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: EspaceMembers,  label: "Category" }
        arguments:
            - ~
            - EspaceMembers\MainBundle\Entity\Category
            - 'SonataAdminBundle:CRUD'

    sonata.admin.event:
        class: EspaceMembers\MainBundle\Admin\EventAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: EspaceMembers,  label: "Event" }
        arguments:
            - ~
            - EspaceMembers\MainBundle\Entity\Event
            - 'SonataAdminBundle:CRUD'

    #TWIG INTL
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    twig.extension.espace_members.filter_extension:
        class: EspaceMembers\MainBundle\Twig\FilterExtension
        tags:
            - { name: twig.extension }

    twig.extension.espace_members.function_extension:
        class: EspaceMembers\MainBundle\Twig\FunctionExtension
        tags:
            - { name: twig.extension }

    twig.extension.espace_members_extension_dump:
        class: EspaceMembers\MainBundle\Twig\DumpyTwigFilter
        tags:
            - { name: twig.extension }

    twig.sonata_media.extension:
        class: EspaceMembers\MainBundle\Twig\MediaExtension
        arguments:
            - @sonata.media.pool
            - @sonata.media.manager.media
            - @sonata.media.twig.extension
            - %sonata_media_cdn_server_path%
            - %kernel.root_dir%
        tags:
            - { name: twig.extension }

    #Doctrine Media Listener
    media_listener:
        class: EspaceMembers\MainBundle\Entity\Listener\MediaListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.orm.entity_listener }

    #Doctrine ParamConverters
    param_converter.teacher_by_event:
        class: EspaceMembers\MainBundle\Request\ParamConverter\TeacherByEventParamConverter
        tags:
            - { name: request.param_converter, converter: teacher_by_event_converter }
        arguments:
            - @?doctrine
