parameters:
    sonata.user.admin.user.class: EspaceMembers\MainBundle\Admin\UserAdmin
    sonata.user.admin.user.entity: Application\Sonata\UserBundle\Entity\User

services:
    getid3:
        class: GetId3\GetId3Core

    sonata.user.admin.group:
        abstract: true
        public: false

    sonata.admin.group:
        class: EspaceMembers\MainBundle\Admin\GroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: EspaceMembers, label: "group_list", label_translator_strategy: sonata.admin.label.strategy.underscore}
        arguments:
            - ~
            - Application\Sonata\UserBundle\Entity\Group
            - 'SonataAdminBundle:CRUD'
        calls:
            - [setTranslationDomain, ['SonataAdminBundle']]

    sonata.admin.teaching:
        class: EspaceMembers\MainBundle\Admin\TeachingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: EspaceMembers, label_catalogue:"SonataAdminBundle",  label: "teaching_list", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - EspaceMembers\MainBundle\Entity\Teaching
            - 'SonataAdminBundle:CRUD'
        calls:
            - [setTranslationDomain, ['SonataAdminBundle']]

    sonata.admin.direction:
        class: EspaceMembers\MainBundle\Admin\DirectionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: EspaceMembers, label_catalogue:"SonataAdminBundle",  label: "direction_list", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - EspaceMembers\MainBundle\Entity\Direction
            - 'SonataAdminBundle:CRUD'
        calls:
            - [setTranslationDomain, ['SonataAdminBundle']]

    sonata.admin.tag:
        class: EspaceMembers\MainBundle\Admin\TagAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: EspaceMembers, show_in_dashboard: false, label_catalogue:"SonataAdminBundle",  label: "tag_list", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - EspaceMembers\MainBundle\Entity\Tag
            - 'SonataAdminBundle:CRUD'
        calls:
            - [setTranslationDomain, ['SonataAdminBundle']]

    sonata.admin.category:
        class: EspaceMembers\MainBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: EspaceMembers, label_catalogue:"SonataAdminBundle",  label: "category_list", label_translator_strategy: sonata.admin.label.strategy.underscore }
        arguments:
            - ~
            - EspaceMembers\MainBundle\Entity\Category
            - 'SonataAdminBundle:CRUD'
        calls:
            - [setTranslationDomain, ['SonataAdminBundle']]

    sonata.admin.event:
        class: EspaceMembers\MainBundle\Admin\EventAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: EspaceMembers, label_catalogue:"SonataAdminBundle",  label: "event_list", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - EspaceMembers\MainBundle\Entity\Event
            - 'SonataAdminBundle:CRUD'
        calls:
            - [setTranslationDomain, ['SonataAdminBundle']]

    #TWIG INTL
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    twig.extension.espace_members.filter_extension:
        class: EspaceMembers\MainBundle\Twig\FilterExtension
        tags:
            - { name: twig.extension }

    twig.extension.espace_members.function_extension:
        class: EspaceMembers\MainBundle\Twig\FunctionExtension
        tags:
            - { name: twig.extension }

    twig.sonata_media.extension:
        class: EspaceMembers\MainBundle\Twig\MediaExtension
        arguments:
            - @sonata.media.pool
            - @sonata.media.manager.media
            - @sonata.media.twig.extension
            - %sonata_media_cdn_server_path%
        tags:
            - { name: twig.extension }

    #Doctrine ParamConverters
    param_converter.teacher_by_event:
        class: EspaceMembers\MainBundle\Request\ParamConverter\TeacherByEventParamConverter
        tags:
            - { name: request.param_converter, converter: teacher_by_event_converter }
        arguments:
            - @?doctrine

    espace.locale_listener:
        class: EspaceMembers\MainBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
