sonata_admin:
    title: EspaceMembers
    security:
        handler: sonata.admin.security.handler.role
    templates:
        layout:              EspaceMembersMainBundle::sonata_admin_base_layout.html.twig
        search:              SonataAdminBundle:Core:search.html.twig
        search_result_block: SonataAdminBundle:Block:block_search_result.html.twig
        user_block:          ApplicationSonataUserBundle:Admin\Core:user_block.html.twig
    dashboard:
        groups:
            EspaceMembers:
                icon:  '<i class="fa ion-ios-gear-outline"></i>'
            user:
                label: user_managments
                items:
                    - sonata.user.admin.user
                roles: [ ROLE_SUPER_ADMIN ]
                icon:  '<i class="fa ion-person-stalker"></i>'
