parameters:
    my_mailer.transport:  sendmail
    espace.media.admin.media.class: Application\Sonata\MediaBundle\Admin\ORM\MediaAdmin

services:
    #Doctrine Media Listener
    media_listener:
        class: Application\Sonata\MediaBundle\Entity\Listener\MediaListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.orm.entity_listener }

    sonata.media.admin.media:
        class: %espace.media.admin.media.class%
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false, label_catalogue: %sonata.media.admin.media.translation_domain% , label_translator_strategy: sonata.admin.label.strategy.underscore }
        arguments:
            - ~
            - %sonata.media.admin.media.entity%
            - %sonata.media.admin.media.controller%
            - "@sonata.media.pool"
            - "@sonata.classification.manager.category"
        calls:
            - [setModelManager, ["@sonata.media.admin.media.manager"]]
            - [setTranslationDomain, [%sonata.media.admin.media.translation_domain%]]
            - [setTemplates, [{ inner_list_row: SonataMediaBundle:MediaAdmin:inner_row_media.html.twig , base_list_field: SonataAdminBundle:CRUD:base_list_flat_field.html.twig , list: SonataMediaBundle:MediaAdmin:list.html.twig , edit: SonataMediaBundle:MediaAdmin:edit.html.twig }]]
