EspaceMembers\MainBundle\Entity\Category:
  type: entity
  repositoryClass: EspaceMembers\MainBundle\Entity\Repository\CategoryRepository
  table: category
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
      unique: true
  oneToMany:
    events:
      targetEntity: EspaceMembers\MainBundle\Entity\Event
      mappedBy: category
      cascade: ["persist", "remove"]
