EspaceMembers\MainBundle\Entity\Direction:
  type: entity
  repositoryClass: EspaceMembers\MainBundle\Entity\Repository\DirectionRepository
  table: direction
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
      unique: true
  manyToMany:
    teachings:
      targetEntity: EspaceMembers\MainBundle\Entity\Teaching
      inversedBy: directions
      cascade: ["persist"]
      joinTable:
        name: teachings_directions
        joinColumns:
          voie_id:
            referencedColumnName: id
        inverseJoinColumns:
          teaching_id:
            referencedColumnName: id
            onDelete: CASCADE
