EspaceMembers\MainBundle\Entity\Group:
    type:  entity
    repositoryClass: EspaceMembers\MainBundle\Entity\Repository\GroupRepository
    table: fos_group
    id:
      id:
        type: integer
        generator:
          strategy: AUTO
    manyToMany:
        events:
          targetEntity: EspaceMembers\MainBundle\Entity\Event
          inversedBy: groups
          cascade: ["persist"]
          joinTable:
            name: groups_events
            joinColumns:
              group_id:
                referencedColumnName: id
                onDelete: CASCADE
            inverseJoinColumns:
              event_id:
                referencedColumnName: id
