EspaceMembers\MainBundle\Entity\Media:
  type: entity
  table: media__media
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    playtime:
        type: string
        length: 15
        nullable: true
  entityListeners:
     EspaceMembers\MainBundle\Entity\Listener\MediaListener:
        prePersist: [prePersistHandler]
