EspaceMembers\MainBundle\Entity\Tag:
  type: entity
  repositoryClass: EspaceMembers\MainBundle\Entity\Repository\TagRepository
  table: tag
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      type: string
      length: 255
      unique: true
  manyToMany:
    teachings:
      targetEntity: EspaceMembers\MainBundle\Entity\Teaching
      inversedBy: tags
      cascade: ["persist"]
      joinTable:
        name: tags_teachings
        joinColumns:
          tag_id:
            referencedColumnName: id
            onDelete: CASCADE
        inverseJoinColumns:
          teaching_id:
            referencedColumnName: id
            onDelete: CASCADE
    events:
      targetEntity: EspaceMembers\MainBundle\Entity\Event
      inversedBy: tags
      cascade: ["persist"]
      joinTable:
        name: tags_events
        joinColumns:
          tag_id:
            referencedColumnName: id
        inverseJoinColumns:
          event_id:
            referencedColumnName: id
            onDelete: CASCADE
