EspaceMembers\MainBundle\Entity\User:
  type: entity
  repositoryClass: EspaceMembers\MainBundle\Entity\Repository\UserRepository
  table: fos_user
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    first_name:
      type: string
      length: 255
      nullable: true
    last_name:
      type: string
      length: 255
      nullable: true
    birthday:
      type: datetime
    description:
      type: text
      nullable: true
    sex:
      type: SexType
      nullable: true
    is_teacher:
      type: boolean
      nullable: true
    address:
      type: string
      length: 255
      nullable: true
  oneToOne:
    avatar:
      targetEntity: EspaceMembers\MainBundle\Entity\Media
      cascade: ["persist"]
      joinColumn:
        name: 
        referencedColumnName: id
        cascade: ["persist"]
        nullable: true
        onDelete: SET NULL
  manyToMany:
    events:
      targetEntity: EspaceMembers\MainBundle\Entity\Event
      inversedBy: users
      cascade: ["persist"]
      joinTable:
        name: users_events
        joinColumns:
          user_id:
            referencedColumnName: id
        inverseJoinColumns:
          event_id:
            referencedColumnName: id
    teachings:
      orderBy: { 'serial': 'ASC' }
      targetEntity: EspaceMembers\MainBundle\Entity\Teaching
      inversedBy: users
      cascade: ["persist"]
      joinTable:
        name: teachings_users
        joinColumns:
          user_id:
            referencedColumnName: id
        inverseJoinColumns:
          teaching_id:
            referencedColumnName: id
    bookmarks:
      orderBy: { 'serial': 'ASC' }
      targetEntity: EspaceMembers\MainBundle\Entity\Teaching
      inversedBy: bookmarkOwners
      cascade: ["persist"]
      joinTable:
        name: bookmarks_users
        joinColumns:
          user_id:
            referencedColumnName: id
        inverseJoinColumns:
          teaching_id:
            referencedColumnName: id
