EspaceMembers\MainBundle\Entity\Voie:
  type: entity
  repositoryClass: EspaceMembers\MainBundle\Entity\Repository\VoieRepository
  table: voie
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      type: string
      length: 255
      unique: true
  manyToMany:
    teachings:
      targetEntity: EspaceMembers\MainBundle\Entity\Teaching
      inversedBy: voies
      cascade: ["persist"]
      joinTable:
        name: teachings_voies
        joinColumns:
          voie_id:
            referencedColumnName: id
        inverseJoinColumns:
          teaching_id:
            referencedColumnName: id
            onDelete: CASCADE
