parameters:
    user_security.login_success_handler.class: EspaceMembers\SecurityBundle\Component\Authentication\Handler\LoginSuccessHandler

services:
    user_security.login_success:
        class:  %user_security.login_success_handler.class%
        arguments:  [@router, @security.context]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
